/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UniApp;

import UniApp.exceptions.PreexistingEntityException;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import java.io.IOException;
import javax.swing.DefaultListModel;

/**
 *
 * @author Cyclo
 */
public class UniApp_JFrame extends javax.swing.JFrame {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("UniAppPU");
    EntityManager em = emf.createEntityManager();
    UniappJpaController controller = new UniappJpaController(emf);
    //δημιουργούμε ένα αντικείμενο OkHttpClient
    private OkHttpClient client = new OkHttpClient();

    /**
     * Creates new form UniApp_JFrame
     */
    public UniApp_JFrame() {
        initComponents();
        //Επιλέγουμε να μας εμφανίζεται στο κέντρο
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Keyword");

        jButton1.setText("Εύρεση βάση ονόματος");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jList1);

        jTextField2.setEditable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField7.setEditable(false);
        jTextField7.setToolTipText("");

        jButton2.setText("Εμφάνισε");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Όνομα");

        jButton3.setText("Εύρεση βάση χώρας");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Τροποποίηση");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Domain");

        jLabel5.setText("Περιοχή");

        jLabel6.setText("Code");

        jLabel7.setText("Τηλέφωνο");

        jLabel8.setText("Χώρα");

        jLabel9.setText("Προβολές");

        jLabel10.setText("Σχόλια");

        jButton5.setText("Στατιστικά");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField2)
                                        .addComponent(jTextField3)
                                        .addComponent(jTextField4)
                                        .addComponent(jTextField5)
                                        .addComponent(jTextField6)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(715, 715, 715)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addComponent(jButton3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addGap(60, 60, 60)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel1.setText("UniApp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Ελέγχουμε αν υπάρχει επιλεγμένο πανεπιστήμιο
        String selectedUniversity = jTextField2.getText();
        if (selectedUniversity == null || selectedUniversity.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Δεν υπάρχει επιλεγμένο πανεπιστήμιο.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Δημιουργούμε ένα transaction στην βάση.
        em.getTransaction().begin();
        //Ψάχνουμε για το συγκεκριμένο πανεπιστήμιο στη βάση
        Uniapp university = controller.findUniapp(selectedUniversity);

        if (university != null) {
            // Ενημερώνουμε τα στοιχεία του πανεπιστημίου με αυτά που έβαλε ο χρήστης
            university.setWebPage(jTextField3.getText());
            university.setState(jTextField4.getText());
            university.setCode(jTextField5.getText());
            university.setCountry(jTextField6.getText());
            university.setViews(Integer.parseInt(jTextField7.getText()));
            university.setPhone(jTextField8.getText());
            university.setComments(jTextField9.getText());

            try {
                //Με το edit αποθηκεύουμε τις αλλαγές
                controller.edit(university);
                //Με το commit οι αλλαγές αποθηκεύονται οριστικά
                em.getTransaction().commit();
                //Εκτυπώνουμε τα ανάλογα μηνύματα
                JOptionPane.showMessageDialog(this, "Οι αλλαγές αποθηκεύτηκαν επιτυχώς!", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                em.getTransaction().rollback();
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Σφάλμα κατά την αποθήκευση των αλλαγών.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Το πανεπιστήμιο δεν υπάρχει στη βάση δεδομένων.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // αποθηκεύουμε σε ένα string ό,τι έχει πληκτρολογήσει ο χρήστης
        String xora = jTextField1.getText().trim();
        //ελέγχουμε αν ο χρήστης έχει πληκτρολογήσει κάτι
        if (xora.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Παρακαλώ εισάγετε χώρα πανεπιστημίου.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //δημιουργούμε το url που θα καλέσουμε
        String urlToCall = "http://universities.hipolabs.com/search?country=" + xora;
        //δημιουργούμε νέο νήμα ώστε να μην κολλήσει το πρόγραμμα σε περίπτωση πχ καθυστέρησης της σύνδεσης
        new Thread(() -> {
            try {
                //δημιουργούμε το request και εκτελούμε το αίτημα
                Request request = new Request.Builder().url(urlToCall).build();
                Response response = client.newCall(request).execute();
                //αν η απάντηση είναι επιτυχής παίρνουμε τα δεδομένα
                if (response.isSuccessful() && response.body() != null) {
                    String responseString = response.body().string();
                    updateList(responseString);
                    //αν η κλήση αποτύχει, εμφανίζει το παρακάτω μήνυμα
                } else {
                    JOptionPane.showMessageDialog(this, "Αποτυχία ανάκτησης δεδομένων.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Σφάλμα κατά τη σύνδεση στο API.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            }
        }
        ).start();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //αποθηκεύουμε το όνομα του πανεπιστημίου σε ένα string
        String selectedUniversity = jList1.getSelectedValue();
        //αν ο χρήστης δεν έχει επιλέξει κάτι εμφανίζει μήνυμα λάθους
        if (selectedUniversity == null) {
            JOptionPane.showMessageDialog(this, "Παρακαλώ επιλέξτε ένα πανεπιστήμιο.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //ξεκινάμε ένα transaction στην βάση δεδομένων
        em.getTransaction().begin();
        //ελέγχουμε μέσω της findUniapp του JpaController αν υπάρχει το πανεπιστήμιο στην βάση δεδομένων
        Uniapp university = controller.findUniapp(selectedUniversity);
        //αν υπάρχει, ενημερώνουμε τις προβολές
        if (university != null) {
            university.setViews(university.getViews() + 1);

            try {
                //ενημερώνει την βάση καλώντας την controller.edit
                controller.edit(university);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            //ολοκληρώνει το transaction
            em.getTransaction().commit();
        } else {
            //αν δεν υπάρχει στην βάση μας κάνει κλήση στο api
            String urlToCall = "http://universities.hipolabs.com/search?name=" + selectedUniversity;
            try {
                //στέλνουμε ένα request
                Request request = new Request.Builder().url(urlToCall).build();
                Response response = client.newCall(request).execute();
                //αν το api επιστρέψει δεδομένα, τα αποθηκεύουμε στην βάση
                if (response.isSuccessful() && response.body() != null) {
                    //αποθηκεύουμε την απάντηση σε ένα string
                    String responseString = response.body().string();
                    //δημιουργούμε ένα αντικείμενο gson το οποίο χρησιμοποιείται για να μετατρέψουμε json σε αντικείμενα java
                    Gson gson = new Gson();
                    //μετατρέπουμε το responsestring σε jsonarray
                    JsonArray jsonArray = gson.fromJson(responseString, JsonArray.class);
                    //ελέγχουμε αν το jsonarray δεν είναι κενό
                    if (jsonArray.size() > 0) {
                        //επιλέγουμε το πρώτο αντικείμενο και το μετατρέπουμε σε jsonobject
                        JsonObject universityJson = jsonArray.get(0).getAsJsonObject();
                        //δημιουργούμε ένα νέο αντικείμενο που θα αποθηκευτεί στη βάση
                        //αν δεν υπάρχει πεδίο, αντικαθιστούμε με unknown
                        university = new Uniapp(
                                //αποθηκεύουμε το όνομα
                                universityJson.get("name").getAsString(),
                                //για τα υπόλοιπα πεδία ελέγχουμε πρώτα αν υπάρχει εγγραφή και αν δεν υπάρχει βάζουμε unknown
                                universityJson.has("web_pages") ? universityJson.get("web_pages").getAsJsonArray().get(0).getAsString() : "Unknown",
                                universityJson.has("state-province") && !universityJson.get("state-province").isJsonNull() ? universityJson.get("state-province").getAsString() : "Unknown",
                                universityJson.has("alpha_two_code") ? universityJson.get("alpha_two_code").getAsString() : "Unknown",
                                universityJson.has("country") ? universityJson.get("country").getAsString() : "Unknown",
                                universityJson.has("domains") ? universityJson.get("domains").getAsJsonArray().get(0).getAsString() : "Unknown",
                                //δίνουμε την τιμή 1 στα views
                                1
                        );

                        try {
                            //αποθηκεύουμε το πανεπιστήμιο στη βάση με try catch σε περίπτωση σφάλματος
                            controller.create(university);
                            em.getTransaction().commit();
                        } catch (Exception e) {
                            e.printStackTrace();
                            JOptionPane.showMessageDialog(this, "Σφάλμα κατά την αποθήκευση στη βάση δεδομένων.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
                //το απαραίτητο try catch για την σύνδεση στο api
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Σφάλμα κατά τη σύνδεση στο API.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            }
        }
        //εμφανίζουμε τα δεδομένα μας στα πεδία
        jTextField2.setText(university.getName());
        jTextField3.setText(university.getWebPage());
        jTextField4.setText(university.getState());
        jTextField5.setText(university.getCode());
        jTextField6.setText(university.getCountry());
        jTextField7.setText(String.valueOf(university.getViews()));
        jTextField8.setText(university.getPhone());
        jTextField9.setText(university.getComments());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // αποθηκεύουμε σε ένα string ό,τι έχει πληκτρολογήσει ο χρήστης
        String onoma = jTextField1.getText().trim();
        //ελέγχουμε αν ο χρήστης έχει πληκτρολογήσει κάτι
        if (onoma.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Παρακαλώ εισάγετε όνομα πανεπιστημίου.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //δημιουργούμε το url που θα καλέσουμε
        String urlToCall = "http://universities.hipolabs.com/search?name=" + onoma;
        //δημιουργούμε νέο νήμα ώστε να μην κολλήσει το πρόγραμμα σε περίπτωση πχ καθυστέρησης της σύνδεσης
        new Thread(() -> {
            try {
                //δημιουργούμε το request και εκτελούμε το αίτημα
                Request request = new Request.Builder().url(urlToCall).build();
                Response response = client.newCall(request).execute();
                //αν η απάντηση είναι επιτυχής παίρνουμε τα δεδομένα
                if (response.isSuccessful() && response.body() != null) {
                    String responseString = response.body().string();
                    updateList(responseString);
                    //αν η κλήση αποτύχει, εμφανίζει το παρακάτω μήνυμα
                } else {
                    JOptionPane.showMessageDialog(this, "Αποτυχία ανάκτησης δεδομένων.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Σφάλμα κατά τη σύνδεση στο API.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
            }
        }
        ).start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Δημιουργούμε το παράθυρο με τα στατιστικά
        UniApp_JFrameStats stats = new UniApp_JFrameStats();
        //Κλείνουμε το αρχικό μας παράθυρο
        this.dispose();
        //Κεντράρουμε το νέο παράθυρο
        stats.setLocationRelativeTo(null);
        //Εμφανίζουμε το παράθυρο
        stats.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed
    private void updateList(String jsonResponse) {
        //χρησιμοποιούμε την gson για να διαβάσουμε την json
        Gson gson = new Gson();
        //μετατρέπουμε την json σε jsonarray
        JsonArray jsonArray = gson.fromJson(jsonResponse, JsonArray.class);
        //δημιουργούμε μια λίστα με τα ονόματα των πανεπιστημίων
        List<String> universityNames;
        universityNames = new ArrayList<>();
        for (int i = 0; i < jsonArray.size(); i++) {
            JsonObject university = jsonArray.get(i).getAsJsonObject();
            //για κάθε αντικείμενο json αποθηκεύει το όνομα.
            if (university.has("name")) {
                universityNames.add(university.get("name").getAsString());
            }
        }
        //ενημερώνουμε την jlist1
        DefaultListModel<String> listModel = new DefaultListModel<>();
        int counter = 0;
        for (String name : universityNames) {
            listModel.addElement(name);
            counter++;

        }

        jList1.setModel(listModel);
        if (counter == 0) {
            JOptionPane.showMessageDialog(this, "Δεν βρέθηκε κανένα πανεπιστήμιο", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
        } else if (counter == 1) {
            JOptionPane.showMessageDialog(this, "Βρέθηκε " + counter + " πανεπιστήμιο", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Βρέθηκαν " + counter + " πανεπιστήμια", "Ενημέρωση", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniApp_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniApp_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniApp_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniApp_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniApp_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
