/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UniApp;

import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.table.DefaultTableModel;
import javax.persistence.Persistence;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
//Βιβλιοθήκες για την δημιουργία pdf
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Cyclo
 */
public class UniApp_JFrameStats extends javax.swing.JFrame {

    /**
     * Creates new form UniApp_JFrameStats
     */
    public UniApp_JFrameStats() {
        initComponents();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("UniAppPU");
        controller = new UniappJpaController(emf); // Δημιουργούμε το controller
        setLocationRelativeTo(null); // Βάζει το παράθυρο στο κέντρο
        loadStatsTable(); // Φορτώνει τα δεδομένα στον πίνακα
    }
    private UniappJpaController controller;

    private void loadStatsTable() {
        //Αποθηκεύουμε σε μία λίστα τα δεδομένα από το query
        List<Object[]> topUniversities = controller.getTopUniversities();
        //Δημιουργούμε ένα νέο μοντέλο
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Πανεπιστήμιο");
        model.addColumn("Προβολές");
        //Αποθηκεύουμε τα στοιχεία από τη λίστα
        for (Object[] row : topUniversities) {
            model.addRow(row);
        }
        //Εμφανίζουμε το μοντέλο στο πίνακα
        jTable1.setModel(model);
    }

    private void exportToPDF() {
        //Δημιουργούμε το αντικείμενο Document
        Document document = new Document();
        try {
            //Δημιουργούμε ένα PDF writer ώστε να γράψουμε στο αρχείο
            PdfWriter.getInstance(document, new FileOutputStream("UniAppStats.pdf"));
            //Ανοίγουμε το αρχείο
            document.open();

            //Δημιουργούμε πίνακα με 2 στήλες
            PdfPTable table = new PdfPTable(2);
            //Δίνουμε ονόματα στις στήλες
            table.addCell("Πανεπιστήμιο");
            table.addCell("Προβολές");

            //Φορτώνουνμε τα δεδομένα από τη βάση
            List<Object[]> topUniversities = controller.getTopUniversities();
            for (Object[] row : topUniversities) {
                table.addCell(row[0].toString()); 
                table.addCell(row[1].toString()); 
            }

            //Βάζουμε τον πίνακα στο PDF
            document.add(table);
            //Κλείνουμε το αρχείο ώστε να δημιουργηθεί το αρχείο
            document.close();
            //Εκτυπώνουμε τα κατάλληλα μηνύματα
            JOptionPane.showMessageDialog(this, "Το αρχείο PDF δημιουργήθηκε επιτυχώς!", "Επιτυχία", JOptionPane.INFORMATION_MESSAGE);

        } catch (DocumentException | IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Σφάλμα κατά τη δημιουργία του PDF.", "Σφάλμα", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Εξαγωγή σε pdf");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Επιστροφή");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        exportToPDF();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Ανοίγουμε ξανά ένα αρχικό παράθυρο
        UniApp_JFrame frame = new UniApp_JFrame();
        //Κλείνουμε το αρχικό μας παράθυρο
        this.dispose();
        //Κεντράρουμε το νέο παράθυρο
        frame.setLocationRelativeTo(null);
        //Εμφανίζουμε το παράθυρο
        frame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniApp_JFrameStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniApp_JFrameStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniApp_JFrameStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniApp_JFrameStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniApp_JFrameStats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
